#pragma once

#include <Features/SkinManager.h>
#include <array>
#include <string_view>

namespace skin_changer {

enum class MusicKit : std::uint16_t {
    CounterStrike2 = 1,
    MusicNotNamed = 2,
    CrimsonAssault = 3,
    Sharpened = 4,
    Insurgency = 5,
    A_D_8 = 6,
    HighNoon = 7,
    DeathsHeadDemolition = 8,
    DesertFire = 9,
    LNOE = 10,
    Metal = 11,
    AllIWantForChristmas = 12,
    IsoRhythm = 13,
    ForNoMankind = 14,
    HotlineMiami = 15,
    The8BitKit = 16,
    TheTalosPrinciple = 17,
    Battlepack = 18,
    Molotov = 19,
    UberBlastoPhone = 20,
    HazardousEnvironments = 21,
    Headshot = 22,
    TotalDomination = 23,
    IAm = 24,
    Diamonds = 25,
    Invasion = 26,
    LionsMouth = 27,
    SpongeFingerz = 28,
    Aggressive = 29,
    JavaHavanaFunkaloo = 30,
    MomentsCSGO = 31,
    Disgusting = 32,
    TheGoodYouth = 33,
    Free = 34,
    LifesNotOutToGetYou = 35,
    Backbone = 36,
    GLA = 37,
    Arena = 38,
    EZ4ENCE = 39,
    Halo = 40,
    KingScar = 41,
    AlxyAntiCitizen = 42,
    Bachram = 43,
    TacoTruck = 44,
    EyeOfTheDragon = 45,
    MUDDForce = 46,
    NeoNoir = 47,
    Bodacious = 48,
    Drifter = 49,
    AllForDust = 50,
    Hades = 51,
    TheLowfilePack = 52,
    ChainsawLxadxut = 53,
    MochaPetal = 54,
    YellowMagic = 55,
    Vici = 56,
    AtroBellum = 57,
    WorkHardPlayHard = 58,
    Kolibri = 59,
    U_Mad = 60,
    FlashBangDance = 61,
    HeadingForTheSource = 62,
    Void = 63,
    Shooters = 64,
    Dashstar = 65,
    GothicLuxury = 66,
    LockMeUp = 67,
    HuaLian = 68,
    Ultimate = 69,
    CSGO = 70,
    UnderBrightLights = 76
};

struct MusicKitInfo {
    std::uint16_t id;
    std::string_view name;
};

constexpr std::array<MusicKitInfo, 71> MUSIC_KITS{{
    {1, "Counter-Strike 2"},
    {2, "Valve CSGO 2 (hidden)"},
    {3, "Crimson Assault"},
    {4, "Sharpened"},
    {5, "Insurgency"},
    {6, "A_D_8"},
    {7, "High Noon"},
    {8, "Death's Head Demolition"},
    {9, "Desert Fire"},
    {10, "LNOE"},
    {11, "Metal"},
    {12, "All I Want For Christmas"},
    {13, "Iso Rhythm"},
    {14, "For No Mankind"},
    {15, "Hotline Miami"},
    {16, "The 8-Bit Kit"},
    {17, "The Talos Principle"},
    {18, "Battlepack"},
    {19, "Molotov"},
    {20, "Uber Blasto Phone"},
    {21, "Hazardous Environments"},
    {22, "Headshot"},
    {23, "Total Domination"},
    {24, "I Am"},
    {25, "Diamonds"},
    {26, "Invasion!"},
    {27, "Lion's Mouth"},
    {28, "Sponge Fingerz"},
    {29, "Aggressive"},
    {30, "Java Havana Funkaloo"},
    {31, "Moments CSGO"},
    {32, "Disgusting"},
    {33, "The Good Youth"},
    {34, "FREE"},
    {35, "Life's Not Out To Get You"},
    {36, "Backbone"},
    {37, "GLA"},
    {38, "Arena"},
    {39, "EZ4ENCE"},
    {40, "Halo"},
    {41, "King, Scar"},
    {42, "Anti-Citizen"},
    {43, "Bachram"},
    {44, "Taco Truck"},
    {45, "Eye of the Dragon"},
    {46, "M.U.D.D. FORCE"},
    {47, "Neo Noir"},
    {48, "Bodacious"},
    {49, "Drifter"},
    {50, "All For Dust"},
    {51, "Hades"},
    {52, "The Lowfile Pack"},
    {53, "CHAINSAW Lxadxut"},
    {54, "Mocha Petal"},
    {55, "Yellow Magic"},
    {56, "VICI"},
    {57, "Atro Bellum"},
    {58, "Work Hard, Play Hard"},
    {59, "Kolibri"},
    {60, "U Mad!"},
    {61, "Flashbang Dance"},
    {62, "Heading For The Source"},
    {63, "Void"},
    {64, "Shooters"},
    {65, "Dashstar*"},
    {66, "Gothic Luxury"},
    {67, "Lock Me Up"},
    {68, "Hua Lian"},
    {69, "Ultimate"},
    {70, "CS:GO"},
    {76, "Under Bright Lights"}
}};

}

